/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173__factory>;
    getContractFactory(
      name: "IERC173Events",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173Events__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "OwnableInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableInternal__factory>;
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "AccessControlAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlAdmin__factory>;
    getContractFactory(
      name: "AccessControlERC2771",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlERC2771__factory>;
    getContractFactory(
      name: "AccessControlInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlInternal__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "IAccessControlAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControlAdmin__factory>;
    getContractFactory(
      name: "IAccessControlEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControlEvents__factory>;
    getContractFactory(
      name: "Diamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Diamond__factory>;
    getContractFactory(
      name: "DiamondCut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondCut__factory>;
    getContractFactory(
      name: "DiamondLoupe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondLoupe__factory>;
    getContractFactory(
      name: "DiamondStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondStorage__factory>;
    getContractFactory(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondCut__factory>;
    getContractFactory(
      name: "IDiamondLoupe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondLoupe__factory>;
    getContractFactory(
      name: "HedgerERC2771",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HedgerERC2771__factory>;
    getContractFactory(
      name: "HedgerOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HedgerOwnable__factory>;
    getContractFactory(
      name: "IMasterAgreement",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMasterAgreement__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "ERC2771Context",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC2771Context__factory>;
    getContractFactory(
      name: "ERC2771ContextOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC2771ContextOwnable__factory>;
    getContractFactory(
      name: "IERC2771Context",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC2771Context__factory>;
    getContractFactory(
      name: "IERC2771ContextAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC2771ContextAdmin__factory>;

    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC173",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173>;
    getContractAt(
      name: "IERC173Events",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173Events>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "OwnableInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableInternal>;
    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "AccessControlAdmin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlAdmin>;
    getContractAt(
      name: "AccessControlERC2771",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlERC2771>;
    getContractAt(
      name: "AccessControlInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlInternal>;
    getContractAt(
      name: "IAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "IAccessControlAdmin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControlAdmin>;
    getContractAt(
      name: "IAccessControlEvents",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControlEvents>;
    getContractAt(
      name: "Diamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Diamond>;
    getContractAt(
      name: "DiamondCut",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondCut>;
    getContractAt(
      name: "DiamondLoupe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondLoupe>;
    getContractAt(
      name: "DiamondStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondStorage>;
    getContractAt(
      name: "IDiamondCut",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondCut>;
    getContractAt(
      name: "IDiamondLoupe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondLoupe>;
    getContractAt(
      name: "HedgerERC2771",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.HedgerERC2771>;
    getContractAt(
      name: "HedgerOwnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.HedgerOwnable>;
    getContractAt(
      name: "IMasterAgreement",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMasterAgreement>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "ERC2771Context",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC2771Context>;
    getContractAt(
      name: "ERC2771ContextOwnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC2771ContextOwnable>;
    getContractAt(
      name: "IERC2771Context",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC2771Context>;
    getContractAt(
      name: "IERC2771ContextAdmin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC2771ContextAdmin>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
