/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC173 } from "./IERC173";
export type { IERC173Events } from "./IERC173Events";
export type { Ownable } from "./Ownable";
export type { OwnableInternal } from "./OwnableInternal";
