/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ownable from "./ownable";
export type { ownable };
import type * as roles from "./roles";
export type { roles };
