/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HedgerERC2771 } from "./HedgerERC2771";
export type { HedgerOwnable } from "./HedgerOwnable";
export type { IMasterAgreement } from "./IMasterAgreement";
