/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  ERC2771Context,
  ERC2771ContextInterface,
} from "../../../contracts/metatx/ERC2771Context";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "trustedForwarder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100155760e3908161001b8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c908163572b6c0514607c5750637da0a87714603457600080fd5b34607957806003193601126079577f019ba45a7698f35665571a35d6bdeafc28bded06b4f8713bcdd23743873f3ebe546040516001600160a01b039091168152602090f35b80fd5b90503460d257602036600319011260d2576004356001600160a01b038181169182900360ce57602093507f019ba45a7698f35665571a35d6bdeafc28bded06b4f8713bcdd23743873f3ebe5416148152f35b8380fd5b5080fdfea164736f6c6343000810000a";

type ERC2771ContextConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC2771ContextConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC2771Context__factory extends ContractFactory {
  constructor(...args: ERC2771ContextConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ERC2771Context> {
    return super.deploy(overrides || {}) as Promise<ERC2771Context>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ERC2771Context {
    return super.attach(address) as ERC2771Context;
  }
  override connect(signer: Signer): ERC2771Context__factory {
    return super.connect(signer) as ERC2771Context__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextInterface {
    return new utils.Interface(_abi) as ERC2771ContextInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2771Context {
    return new Contract(address, _abi, signerOrProvider) as ERC2771Context;
  }
}
