/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAccessControlAdmin,
  IAccessControlAdminInterface,
} from "../../../../contracts/access/roles/IAccessControlAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "grantAdminRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    name: "grantSignerRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAccessControlAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IAccessControlAdminInterface {
    return new utils.Interface(_abi) as IAccessControlAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAccessControlAdmin {
    return new Contract(address, _abi, signerOrProvider) as IAccessControlAdmin;
  }
}
